language: python
sudo: false

matrix:
  include:
    - python: 2.7
      env:
        - TOXENV=py27
        - TOXENV=system-tests
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env:
        - TOXENV=py35
        - TOXENV=lint
    - python: 3.6
      env:
        - TOXENV=py36
        - TOXENV=system-tests

install:
  - pip install --upgrade pip
  - pip install --upgrade tox

script:
  - tox

after_success:
  - scripts/coveralls.sh

cache:
  directories:
    - ${HOME}/.cache/pip
